# Use an official Node runtime as the base image
FROM node:latest

# Set the working directory in the container to /usr/src/app
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Make port 4000 available to the world outside this container
EXPOSE 4000

# Run Nodeserver.js when the container launches
CMD [ "node", "nodeserver.js" ]